bloodbank/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Paypal import views as pay

urlpatterns = [
                  path('display/', include('display.urls')),
                  path('stock/', include('stock.urls')),
                  path('credits/', include('credits.urls')),
                  path('home/', include('home.urls')),
                  path('pathlab/', include('pathlab.urls')),
                  path('admin/', admin.site.urls),
                  path('find-donor/', include('finddonor.urls')),
                  path('requestblood/', include('requestblood.urls')),
                  path('availability/', include('availability.urls')),
                  path('bloodcamp/', include('bloodcamp.urls')),
                  # path('hospitals/', include('Hospitals.urls')),
                  path('donate/', include('donate.urls')),
                  path('near-you/', include('maps.urls')),
                  re_path(r'^', include('django.contrib.auth.urls')),
                  path('paypal/', include('paypal.standard.ipn.urls')),
                  path('payment-button/', pay.payment_button, name='payment-button'),
                  path('hospitals/', include('Hospitals.urls')),
                  path('requestor/', include('requestor.urls')),

                  ## Rest API :
                  path('rest/', include('RestFramework.urls'), name='rest'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views
# from django.contrib.auth.views import logout_views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.SignUp, name="signup"),
    path('login/', views.LogIn, name="login"),
    path('logout/', views.user_logout, name="user_logout"),
    path('about/', views.about, name="about"),
    path('profile/', views.profile, name="profile"),
    path('upload/', views.Image_Upload, name="image_upload"),
    path('update_details/', views.Update_Details, name="update_details"),
    path('update_password/', views.Update_Password, name="update_password"),
    path('faq/', views.faq, name="faq"),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),

    path('readmore/',views.readmore,name="readmore"),
    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name="password_reset"),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    re_path(r'^password_reset/complete/$', auth_views.PasswordResetCompleteView.as_view(),
            name="password_reset_complete"),
    re_path(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),

]

pathlab/urls.py
from django.urls import path
from . import views

app_name = "pathlab"

urlpatterns = [
    path('', views.index,name='index'),
    path('result', views.result, name = "result"),
    path('booko', views.booko, name = "booko"),
    path('history', views.history, name = "history"),
    path('report/<int:rid>', views.report, name = "report"),
    path('api/', views.PathLabUser2class.as_view()),
]

pathlab/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from home.models import *

Blood_Groups = (
    ('A+', 'A+'),
    ('A-', 'A-'),
    ('B+', 'B+'),
    ('B-', 'B-'),
    ('O+', 'O+'),
    ('O-', 'O-'),
    ('AB+', 'AB+'),
    ('AB-', 'AB-'),
)

Test_Type = (
    ('Regular Checkup1', 'Regular Checkup1'),
    ('Regular Checkup2', 'Regular Checkup2'),
    ('Regular Checkup3', 'Regular Checkup3'),
)

'''class PathLabUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pathlab = models.ForeignKey(PathLabs, on_delete=models.CASCADE)
    testtype = models.CharField(blank=False, max_length=1000)
    feedback = models.CharField(blank=True, max_length=1000)

    def __str__(self):
        return self.user
'''

class PathLabUser2(models.Model):
    profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    firstname = models.CharField(null=False, max_length=1000)
    lastname = models.CharField(null=True, max_length=1000)
    address = models.CharField(null=False, max_length=1000)
    bloodgroup = models.CharField(null=False, choices=Blood_Groups, max_length=3)
    testtype = models.CharField(null=False, max_length=1000, choices=Test_Type)
    date = models.DateTimeField(auto_now_add=True)
    Result = models.CharField(null=False, max_length=1000, default='NA')
    feedback = models.CharField(null=False, max_length=1000, default='NA')

    def __str__(self):
        return self.firstname

pathlab/forms.py
from django import forms
from .models import PathLabUser2
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.http import HttpResponse


'''class PathlabForm(forms.ModelForm):
    class Meta:
        model = PathLabUser
        fields = ['testtype']
'''

class PathlabForm2(forms.ModelForm):
    class Meta:
        model = PathLabUser2
        fields = ['firstname', 'lastname', 'address', 'bloodgroup', 'testtype']

pathlab/views.py
from django.shortcuts import render
from .models import PathLabUser2
from .forms import PathlabForm2
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.contrib.auth.models import User
from home.models import UserProfile
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import PathLabUser2serializer
from rest_framework.views import APIView
from rest_framework import viewsets
from rest_framework import status



@login_required(login_url='/home/login')
def index(request):
    return render(request, 'pathlab/index.html')


@login_required(login_url='/home/login')
def booko(request):
    if request.method == 'POST':
        form = PathlabForm2(request.POST)
        #form = NameForm(request.POST)
        if form.is_valid():
            result = PathLabUser2.objects.all()
            context = {'result': result, 'form': form, }
            return render(request, 'pathlab/booko.html', context)

    else:
        form = PathlabForm2()
    return render(request, 'pathlab/booko.html', {'form': form})


@login_required(login_url='/home/login')
def result(request):
    if request.method == "POST":
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        address = request.POST['address']
        bloodgroup = request.POST['bloodgroup']
        testtype = request.POST['testtype']
        user = request.user
        if user.is_authenticated:
            p = UserProfile.objects.get(user = user)

            PathLabUser2.objects.create(firstname=firstname, lastname=lastname, address=address, bloodgroup=bloodgroup, testtype=testtype, profile=p)
        print("oihnohnon")
        email = user.email

        send_mail(
            'Blood Test Booked',
            'Your request for Blood Test is received and it is being processed. \n'
            'Details: \n'
            'Name          :' + str(firstname) + str(lastname) + '\n' +
            'Blood Group   :' + str(bloodgroup) + '\n' +
            'Test Type     :' + str(testtype) + '\n',
            'kartikkapoor13@gmail.com',
            [email],
            fail_silently = False,
            )

    return render(request, 'pathlab/result.html')

@login_required(login_url='/home/login')
def history(request):
    datalist = {}
    user = request.user
    if user.is_authenticated:
        p = UserProfile.objects.get(user = user)
        result = PathLabUser2.objects.filter(profile=p)
    #print(result)        #print(datalist)
    #print(datalist)

    context = {'result': result}
    return render(request, 'pathlab/history.html', context)


@login_required(login_url='/home/login')
def report(request, rid):
    reports = PathLabUser2.objects.get(id=rid)
    context = {'reports': reports}
    return render(request, 'pathlab/report.html', context)

#@login_required(login_url='/home/login')
class PathLabUser2class(APIView):
    def get(self, request):
        datalog = PathLabUser2.objects.all()
        serializer = PathLabUser2serializer(datalog, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = PathLabUser2serializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        return Response(serializer.data,status=status.HTTP_400_BAD_REQUEST)


'''class PathLabUser2class(viewsets.ModelViewSet):
    queryset = PathLabUser2.objects.all()
    serializer_class = PathLabUser2serializer'''

pathlab/templates/pathlab/booko.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block head %}
<title>Pathlab | Book Bloodtest</title>
{% endblock %}

{% block body %}
<body style="background-color: rgba(10%, 10%, 100%, 0.15)">
    <div>
        <br><br>
        <div class="container bodysize justify-content-left">
          <div class="row col-12">

        <h2 style="">Please choose the test to conduct</h2>
        <div style="width: 60%">

            <form method="post" action= "{% url 'pathlab:result' %}"  id="book" style="margin: 100px;">

                {% csrf_token %}

                {{ form|crispy }}
                       <br><br><br>
                <tr><label><button class="btn btn-success" type="submit">Request</button></label></tr>

            </form>

        </div>
    </div>
    </div>
</body>
{% endblock %}

pathlab/templates/pathlab/history.html
{% extends 'home/base.html' %}
{% block head %}
    <meta charset="utf-8">
    <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }

    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }

    th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
      background-color: rgba(10%, 10%, 100%, 0.5);
    }

    tr:nth-child(even) {
      background-color: rgba(10%, 10%, 100%, 0.3);
    }

    tr:hover {
      background-color: #dddddd;
    }
  </style>
    <title></title>
{% endblock %}
{% block body %}
  <body style="background-color: rgba(10%, 10%, 100%, 0.15)">

    {% if user.is_authenticated %}
    <h1 style="font-size: 80px; margin: 30px"> History of Blood Tests </h1>
    <table>
      <tr>
        <th> Date </th>
        <th> First Name </th>
        <th> Last Name </th>
        <th> Blood Group </th>
        <th> Test Type </th>
        <th> Result </th>
      </tr>
      <tr>

        {% for item in result %}
        <form action= "{% url 'pathlab:report' item.pk %}" method="post">
        <td>{{ item.date }}</td>
        <td>{{ item.firstname }}</td>
        <td>{{ item.lastname }}</td>
        <td>{{ item.bloodgroup }}</td>
		<td>{{ item.testtype }}</td>
        <td>{{ item.result }} {% csrf_token %} <button class="btn btn-success" type="submit">Check Report</button></td>
	    </form>
      </tr>
		{% endfor %}
	{% endif %}
    </table>
  </body>
{% endblock %}
</html>

pathlab/templates/pathlab/report.html
{% extends 'home/base.html' %}

{% block head %}
<title>Pathlab | Report</title>
<style media="screen">
  .bodysize {background-color: rgba(10%, 10%, 100%, 0.35);
    color:black;
    height : 800px;
    width: 1280px;
  }
</style>
{% endblock %}

{% block body %}
<body style="background-color: rgba(10%, 10%, 100%, 0.15)">
<br><br><br>

<div class="container bodysize justify-content-left">
  <div class="row col-12">
  <table class="table">
  <br>

    <tr>
      <th><h1 style="font-size: 80px">Blood Source Pathlab</h1></th>
    <td></td>
    </tr>

    <tr>
        <th><h1>Blood Test Report</h1></th>
    <td></td>
    </tr>
    <tr>
    <td>First Name:</td>
    <td>{{reports.firstname}}</td>
    </tr>
    <tr>
    <td>Last Name:</td>
    <td>{{reports.lastname}}</td>
    </tr>

    <tr>
    <td>Date of Booking:</td>
    <td>{{reports.date}}</td>
    </tr>
    <tr>
    <td>Bloodgroup:</td>
    <td>{{reports.bloodgroup}}</td>
    </tr>
    <tr>
    <td>Test Type:</td>
    <td>{{reports.testtype}}</td>
    </tr>
    <tr>
    <td>Report:</td>
    <td>{{reports.Result}}</td>
    </tr>
    <tr>
    <td>Feedback:</td>
    <td>{{reports.feedback}}</td>
    </tr>
  </table>

</div>
</div>

{% endblock %}

pathlab/templates/pathlab/result.html
{% extends 'home/base.html' %}
{% block title %}
    Pathlab | Test Booked
{% endblock %}
{% block body %}
<body style="background-color: rgba(10%, 10%, 100%, 0.3)">
    <div>
        <br><br>
        <h2 style = "margin: 50px">&nbsp;&nbsp;&nbsp;Your Test is booked<br><br>&nbsp;&nbsp;&nbsp;A confirmation e-mail has been sent to you.<br><br>&nbsp;&nbsp;&nbsp;Your bill amount is 500/-<br><br>&nbsp;&nbsp;&nbsp;You can Pay the bill now or Pay at the time of collection of blood sample.</h2>

        <div style="float: left ; width: 40%">
            <form method="post" action= "{% url 'payment-button' %}"  id="book" style="margin: 100px;">
                {% csrf_token %}
                <button class="btn btn-success" type="submit">Pay Now</button>
            </form>
        </div>

        <div style="float: left ; width: 60%">
            <form method="post" action= "{% url 'pathlab:index' %}"  id="book" style="margin: 100px;">
                {% csrf_token %}
                <button class="btn btn-success" type="submit">Pay Later</button>
            </form>
        </div>
    </div>
    <br><br><br><br><br><br>
</body>

{% endblock %}